### ISSUE TITLE
Can you provide the performance based on the GT boxes?

### ISSUE THREAD

**Issue by Weiyun1025** [JialianW/GRiT#11]
I notice that you present the results of  in Table 1 of the paper, but these results are based on the bounding boxes predicted by your foreground object extractor, which might lead to error propagations.

As a result, the real performance of the text decoder is not clear and underestimated. So I'm curious about the real performance of the text decoder. Can you provide the performance based on the GT boxes?

**Comment by xk-huang** [comment]
Hi, @Weiyun1025! 

I've checked the results in All-Seeing, and its performance is quite good. Would you mind sharing the code of promptable GRiT? 

Thanks in advance!

**Comment by xk-huang** [comment]
> Hi, @Weiyun1025!
> 
> I've checked the results in All-Seeing, and its performance is quite good. Would you mind sharing the code of promptable GRiT?
> 
> Thanks in advance!

I've released an app for promptable GRiT https://github.com/xk-huang/Promptable-GRiT.

**Comment by Weiyun1025** [comment]
> > Hi, @Weiyun1025!
> > I've checked the results in All-Seeing, and its performance is quite good. Would you mind sharing the code of promptable GRiT?
> > Thanks in advance!
> 
> I've released an app for promptable GRiT https://github.com/xk-huang/Promptable-GRiT.

Thank you for your interest in our work and for sharing the code!

To assess the performance of the GRiT model, we directly modified the code within this repository, so that we can input the ground truth boxes to the model and skip the post-processing steps for these boxes. As our objective is evaluation rather than deployment, we do not currently have a polished version of the code that is ready for release.

We believe that your code will be highly beneficial for others who are also interested in the GRiT model!
