### ISSUE TITLE
third_party project gitmodules

### ISSUE THREAD

**Issue by dashesy** [JialianW/GRiT#2]
Under third_party/Centernet2 there is detectron2 and yet anohter project/Centernet2 
The installation however requires installing detecton2 separately.

It is a little confusing as what is needed and what is not in the gitsubmodule

**Comment by JialianW** [comment]
As shown in the installation instruction, we only need to install detectron2 once for GRiT. There is no need to install the detectron2 under the thrid_party.

There is no need to take care of the installations under the thrid_party folder. The reason for the repeated projects is that we simply copy the Centernet2 project without modifications to the thrid_party following https://github.com/facebookresearch/Detic/tree/85f289b33631cd206de00d6ad9026d8565efb3c0.
