### ISSUE TITLE
Question about the training time 

### ISSUE THREAD

**Issue by Solacex** [JialianW/GRiT#5]
Hey,

Thanks for your inspiring work.
How long will the training take with 8 x A100 GPUs?

**Comment by WaikeiGum** [comment]
Training Dense Captioning on VG Dataset takes me nearly 4 days on 4 RTX3090 GPUs

**Comment by Solacex** [comment]
Okay, thanks for your response.

**Comment by Solacex** [comment]
> Training Dense Captioning on VG Dataset takes me nearly 4 days on 4 RTX3090 GPUs

Do you train the model successfully? Have you met this problem? https://github.com/JialianW/GRiT/issues/1

**Comment by WaikeiGum** [comment]
> 

Yes I have once met the same problem while training on object detection task. And I haven't solved it yet.
It seems to work for training dense captioning task.
I'm still running the code, and it hasn't report any error yet.
