### ISSUE TITLE
Willing to share the original annotations of Visual Genome dataset ?

### ISSUE THREAD

**Issue by ImmortalSdm** [JialianW/GRiT#8]
Sorry to bother you, but seems the official website is down, and i need to use the official annotations of dense caption. I'm hoping that you can share the annotations, it will be very useful. Thx a lot~

**Comment by WaikeiGum** [comment]
> Sorry to bother you, but seems the official website is down, and i need to use the official annotations of dense caption. I'm hoping that you can share the annotations, it will be very useful. Thx a lot~

You could try to download it [here](https://aistudio.baidu.com/aistudio/datasetdetail/57396)

**Comment by ImmortalSdm** [comment]
> > Sorry to bother you, but seems the official website is down, and i need to use the official annotations of dense caption. I'm hoping that you can share the annotations, it will be very useful. Thx a lot~
> 
> You could try to download it [here](https://aistudio.baidu.com/aistudio/datasetdetail/57396)

Thx a lot for your help!
